#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x733A866882A3F5F6 (jeanfi@gmail.com)
#
Name     : psensor
Version  : 1.2.1
Release  : 3
URL      : https://wpitchoune.net/psensor/files/psensor-1.2.1.tar.gz
Source0  : https://wpitchoune.net/psensor/files/psensor-1.2.1.tar.gz
Source1  : https://wpitchoune.net/psensor/files/psensor-1.2.1.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: psensor-bin = %{version}-%{release}
Requires: psensor-data = %{version}-%{release}
Requires: psensor-license = %{version}-%{release}
Requires: psensor-locales = %{version}-%{release}
Requires: psensor-man = %{version}-%{release}
BuildRequires : cppcheck
BuildRequires : help2man
BuildRequires : lm-sensors-dev
BuildRequires : pkgconfig(appindicator3-0.1)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libatasmart)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libgtop-2.0)
BuildRequires : pkgconfig(libmicrohttpd)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(udisks2)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)

%description
:docinfo2:
:toc:
:icons: font
Introduction
------------
Psensor is a graphical hardware monitoring application for Linux.

%package bin
Summary: bin components for the psensor package.
Group: Binaries
Requires: psensor-data = %{version}-%{release}
Requires: psensor-license = %{version}-%{release}

%description bin
bin components for the psensor package.


%package data
Summary: data components for the psensor package.
Group: Data

%description data
data components for the psensor package.


%package doc
Summary: doc components for the psensor package.
Group: Documentation
Requires: psensor-man = %{version}-%{release}

%description doc
doc components for the psensor package.


%package license
Summary: license components for the psensor package.
Group: Default

%description license
license components for the psensor package.


%package locales
Summary: locales components for the psensor package.
Group: Default

%description locales
locales components for the psensor package.


%package man
Summary: man components for the psensor package.
Group: Default

%description man
man components for the psensor package.


%prep
%setup -q -n psensor-1.2.1
cd %{_builddir}/psensor-1.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605726198
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1605726198
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/psensor
cp %{_builddir}/psensor-1.2.1/COPYING %{buildroot}/usr/share/package-licenses/psensor/5821ee1deba963c8e12c6af89224de0d0d47bb53
%make_install
%find_lang psensor

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/psensor
/usr/bin/psensor-server

%files data
%defattr(-,root,root,-)
/usr/share/applications/psensor.desktop
/usr/share/glib-2.0/schemas/psensor.gschema.xml
/usr/share/icons/hicolor/128x128/apps/psensor.png
/usr/share/icons/hicolor/14x14/apps/psensor.png
/usr/share/icons/hicolor/16x16/apps/psensor.png
/usr/share/icons/hicolor/22x22/apps/psensor.png
/usr/share/icons/hicolor/24x24/apps/psensor.png
/usr/share/icons/hicolor/256x256/apps/psensor.png
/usr/share/icons/hicolor/32x32/apps/psensor.png
/usr/share/icons/hicolor/48x48/apps/psensor.png
/usr/share/icons/hicolor/64x64/apps/psensor.png
/usr/share/icons/hicolor/scalable/apps/psensor.svg
/usr/share/icons/hicolor/scalable/apps/psensor_hot.svg
/usr/share/icons/hicolor/scalable/apps/psensor_normal.svg
/usr/share/icons/ubuntu-mono-dark/apps/22/psensor.svg
/usr/share/icons/ubuntu-mono-dark/status/22/psensor_hot.svg
/usr/share/icons/ubuntu-mono-dark/status/22/psensor_normal.svg
/usr/share/icons/ubuntu-mono-light/status/22/psensor_hot.svg
/usr/share/icons/ubuntu-mono-light/status/22/psensor_normal.svg
/usr/share/psensor/psensor-appindicator.glade
/usr/share/psensor/psensor-pref.glade
/usr/share/psensor/psensor.glade
/usr/share/psensor/sensor-edit.glade
/usr/share/psensor/www/details.html
/usr/share/psensor/www/favicon.ico
/usr/share/psensor/www/index.html
/usr/share/psensor/www/jqplot.css
/usr/share/psensor/www/jqplot.dateAxisRenderer.js
/usr/share/psensor/www/jqplot.js
/usr/share/psensor/www/jquery.js
/usr/share/psensor/www/psensor.js
/usr/share/psensor/www/style.css

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/psensor/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/psensor/5821ee1deba963c8e12c6af89224de0d0d47bb53

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/psensor-server.1
/usr/share/man/man1/psensor.1

%files locales -f psensor.lang
%defattr(-,root,root,-)

